### ISSUE TITLE
Why is terminal = False?

### ISSUE THREAD

**Issue by juanma9613** [jviquerat/drl_shape_optimization#1]
Hi, great idea to use PPO to design stuff! 

I'm a Master's degree student at Eafit University (Colombia). jmunozb@eafit.edu.co

I got interesting in your research and I want to try to use the one step PPO to design fourbar mechanisms for my master's thesis (giving the proper citations and credit to your repo and paper)

I was trying to adapt a version changing the scripts environment.py and launch_parallel_training.py but it's not giving the results that I expected. 

I would really like to get it working but I have some doubts: the first one is why did you return 'terminal=False' even though it's a single step PPO? Could you please help me to clarify this? I also saw that in the paper you mentioned that the advantage estimation was only the current reward because the other two prediction terms cancel each other 
Aπ(st, at) = reward_t + γV (st+1) − V (st),. But I wasn't able to tell how you got rid of the critic in the agent code.

https://github.com/jviquerat/drl_shape_optimization/blob/master/src/environment.py#L227

Apart from that I offer an invitation to work together if you are interested in testing you work on another domain.

Thank you and sorry for the long message but I got really interested in the work that you did!

**Comment by jviquerat** [comment]
Hi @juanma9613,

Thank you for showing interest in this work.
It's now been quite some time since I wrote the code, but as far as I remember: 

- `terminal=False` is not a problem, as we force `nb_ctrls_per_episode` here: 

https://github.com/jviquerat/drl_shape_optimization/blob/d3b7ed73d1cd2263380e049c5c29b6cbf256c36a/src/launch_parallel_training.py#L93-L96

and set it to 0 here (there is an off-by-one count, so that leads to a single control step):

https://github.com/jviquerat/drl_shape_optimization/blob/d3b7ed73d1cd2263380e049c5c29b6cbf256c36a/src/parametered_env.py#L20-L26

so that ends the episode after one control anyway.

- Regarding cancelling of critic term, the input state is always the same, so gamma=1 must lead to cancellation of the value terms. I am unable to find where this was set in the code today, as it has been quite some time now.

- This was anyway a preliminary study, and we have just issued a largely improved version of the method <a href="https://arxiv.org/abs/2104.06175">here</a>. The code is not available yet though, but that can be discussed.

- Could you elaborate (through email) on your project ? You can reach me at jonathan.viquerat@mines-paristech.fr
