### ISSUE TITLE
Replacing CFD solver with alternative like xfoil

### ISSUE THREAD

**Issue by zonexo** [jviquerat/drl_shape_optimization#5]
Hi, is it possible to replace the CFD solver with alternatives like xfoil?

Of cos, it may not be as accurate but for some cases, it can be valid and gives fast speed up.

Thanks!

**Comment by jviquerat** [comment]
@zonexo yes, at some point in the process of this project, I thought about using xfoil, although I do not really know the existing assumptions behind the potential-based approach it uses.
Also, as stated in the other issue, I would advise in favour of PBO instead of the present algorithm, mostly for performance.
